services:
  flask-application:
   build:
     context: FlaskApplication
     dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-application